# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
puts "Cleaning Database"
Ticket.destroy_all
Station.destroy_all
User.destroy_all
Itinerary.destroy_all
puts "Database Clean"

puts "Creating seeds"

user_one = User.create(email: "test1@gmail.com", password: "1234567")
user_two = User.create(email: "test2@gmail.com", password: "1234567")
user_three = User.create(email: "test3@gmail.com", password: "1234567")

Station.create(name: "Port Louis Victoria Central", image_url: "https://doc-0g-04-mymaps.googleusercontent.com/untrusted/hostedimage/ou6c6r4ot251igcmt16atv0meo/7qkv0lbcasp63b3ksk8de8q8s4/1663069500000/lU_O4jlGNaHVZq3aQyWXZYVjF9e8lyDa/*/6AFzc1vZulfCWseEXGqt2nfkrKqkY4xbuwUI0PhTSR_rfT8dDl4YOr8kkkKn7gsggdiynbOwxkgotPsvt4M8uR10tnZK2ZPAFWskreiVovjIWW15FE_-ZQ_2g_VILE3XSqTwVx8h82orEwsG4PZn4LL-cgcMuM9mcNxBWQhdO4rvW0gkyPrMsoibUH4wr8IGDyrtb1g_r?fife=s16383", latitude: -20.1624375, longitude: 57.4984168)
Station.create(name: "St Louis Station", image_url: "https://doc-0k-04-mymaps.googleusercontent.com/untrusted/hostedimage/ou6c6r4ot251igcmt16atv0meo/ibquuv0433g7v8mvo7e4nrqs00/1663069500000/lU_O4jlGNaHVZq3aQyWXZYVjF9e8lyDa/*/6AFzc1vbOLotR47bh5UE9eTWjaT8zY8bGuOaFNrUBbiVt82pi-Tociv-3vKKLfY4pkz-VXYGnlUt6Ux1l1sdTmz1Kaq8HelY7XAZG2qvohVGlshahbOXhgjf_QO4s3Gf3dgK9aKsnWPOXIc2GAmnYbIisJ0I2TOTiFO5z4IXbkeye6QlCsFpgSFM0en4Xi6U8Agx3JdZi?fife=s16383", latitude: -20.1809224, longitude: 57.476807)
Station.create(name: "Coromandel Station", image_url: "https://doc-00-04-mymaps.googleusercontent.com/untrusted/hostedimage/ou6c6r4ot251igcmt16atv0meo/tr81mtqrf0pitl99fr4gdruduo/1663069500000/lU_O4jlGNaHVZq3aQyWXZYVjF9e8lyDa/*/6AFzc1vbQxzxhAJvkchDZBzvVL2kZQMO4ncBGuX_Z1bA6s5RbfnGf1vmOGtm3KuYSmbytxBWBcLTgKuR7_PZyZ7_x3w9o5uiiDY3ZM_XTD9vmtG9NIZ73V3fDOJXCbQrlr7TP8RuDKjbgvwgFJvhzBf3lvNM-aRWuLGu_WSCdf3XWkGdR9rFOjJaVSs2EkUfbc1I-oaKw?fife=s16383", latitude: -20.1836331, longitude: 57.4696472)
Station.create(name: "Barkly Station", image_url: "https://doc-14-04-mymaps.googleusercontent.com/untrusted/hostedimage/ou6c6r4ot251igcmt16atv0meo/7up4rs3baqt99tqk8hbs5c5ass/1663069500000/lU_O4jlGNaHVZq3aQyWXZYVjF9e8lyDa/*/6AFzc1vb34NdaZI37aHvQRR7mQqmpHjhF5KDH27vnq_EZz3N88XcdyIm8CedSuL0f_fhZqVqOH4bTGbB8RZWVq3YMbuGaKt2iiI7MduNTJtX-IvqWXfwuT0bDTOPSH3RprxtGW2Dg2AN1Czt83eeaY0WzizOAA7LTMySa_KPWBu5h0ugXy7DqEKKjoOeCrEY8ssGqK1MI?fife=s16383", latitude: -20.2208957, longitude: 57.4584738)
Station.create(name: "Beau Bassin Station", image_url: "https://doc-0c-04-mymaps.googleusercontent.com/untrusted/hostedimage/ou6c6r4ot251igcmt16atv0meo/f0li0jjkttm4j8abs4ru39v3ss/1663069500000/lU_O4jlGNaHVZq3aQyWXZYVjF9e8lyDa/*/6AFzc1vZNeGcxy51ExOYMWuCTa_SsulshvHXafz_J6vi0d8eYm4kEuJuVEdzhe4vB2Z6eAI7SjMevDSrXT3f75X-5eNKSH5WGyahp_I2JAN1KnwLXVHc-opETFzIRMl4iVZWDq-lYtoyt9RWdcwXUChqY8UZHN_Hdo5tCFdLyUWItE7YvEOGSGuJMvYGgibELYvR2BrUx?fife=s16383", latitude: -20.2267401, longitude: 57.4674423)
Station.create(name: "Vandermeersch Station", image_url: "https://doc-00-04-mymaps.googleusercontent.com/untrusted/hostedimage/ou6c6r4ot251igcmt16atv0meo/h6otrsn4rknlnm9plfjq0jdbbk/1663069500000/lU_O4jlGNaHVZq3aQyWXZYVjF9e8lyDa/*/6AFzc1vbBs3QDCExgggewaetLkC3uM20Tyu5PWfq78ZTj_ykV1CSiXgvktuf_KQaKW-NZwUwvYog0XaiiPDMsfWR5uc6GlCZvj0FDoSnPEA2B-_Xdgfrk8ELxRA5LT7gbZTTtW1nn6IZo9eUppyDW9VeOveb6Lp7SAfQX5bwb4V4NwsTR9i6waRcrvCLxCfjGZHxBkjTQ?fife=s16383", latitude: -20.2354432, longitude: 57.4731347)
Station.create(name: "Rose-Hill Central", image_url: "https://doc-0k-04-mymaps.googleusercontent.com/untrusted/hostedimage/ou6c6r4ot251igcmt16atv0meo/kn76fmeola2u5a5adrrteb0la4/1663069500000/lU_O4jlGNaHVZq3aQyWXZYVjF9e8lyDa/*/6AFzc1vYK6HzmNi4y5RuhNlUhCfZN9Vh59vB5ufeIcKjPkb_cNq7QMoJIdJlgftycEsPtq3sfP9VMSd2VnXoKDLM6BzklAKHToi_UK-7iPuRy8BfwSiRjsOD9kKQfumdkxyFVjD3ktPlZmbzCakeuRb_9nOeduGHS-wQ2UTZFw6zUqrEKhMiOBbcEuBM14UVdBSbnbhh_?fife=s16383", latitude: -20.2418811, longitude: 57.4759577)
Station.create(name: "Belle Rose Station", image_url: "https://doc-0k-04-mymaps.googleusercontent.com/untrusted/hostedimage/ou6c6r4ot251igcmt16atv0meo/1gtjeovolsot3cg66p8paa8d40/1663069500000/lU_O4jlGNaHVZq3aQyWXZYVjF9e8lyDa/*/6AFzc1vZtF2oxlg6nAL-py1_JZNksB_UyNL0EfDjQQZPy10O6XVYqRL6kRMb4qN5G0opTsVf57TOOE7SBm4pGJ6FGaRDXd8kLReWJ4xxV4dcsUZYLtxQMOzdCFCrh9hACuxtDqu51Jw3jRgje1dWl1QqnFZt8Wuq8kQN0DTXQfR0hbSkUsJoK_C0UA111GvukKGFmlbIO?fife=s16383", latitude: -20.2535275, longitude: 57.4777101)
Station.create(name: "Quatre Bornes Central", image_url: "https://doc-14-04-mymaps.googleusercontent.com/untrusted/hostedimage/ou6c6r4ot251igcmt16atv0meo/v18ihlb4kcdp3h10cje8uj5058/1663069500000/lU_O4jlGNaHVZq3aQyWXZYVjF9e8lyDa/*/6AFzc1vbmuED8D3bHqke3BUtvWi4vRnYwKacfa38WmZM4GMcOnTPwtwmmfUGLFQoqTnEGmhc5hhRF0Evcl613_erM2T9C_ltX6sGPx8WbH2o7oGqoYrDE270s1u5vGsSr-IgzMFQ7XoknoAfVYe8Zg2wOWeCObOrQ0xdlumbf8PFGcelAbIJSupsrKal84CzIBft_wsEW?fife=s16383", latitude: -20.2653165, longitude: 57.4784026)
Station.create(name: "St Jean Station", image_url: "https://doc-08-04-mymaps.googleusercontent.com/untrusted/hostedimage/ou6c6r4ot251igcmt16atv0meo/scnf3nnbh0rcmrs7s5fgfltg2k/1663069500000/lU_O4jlGNaHVZq3aQyWXZYVjF9e8lyDa/*/6AFzc1vajp_Tgua__qP1paqJneDHYcfu2chaC8YiB6AvJX-0OMtNmI5pArPk4Fd9BA-YnjtpUI1Jik4zUBCZGbAgO5Q5jsv8_mtfiqNX6aKZmufE9j3DblwwfN-RSh0HRK0TYK8Wsyb-_lg3dCeU_NMw7SxQtIweNUtvhJPhaTMyxipL0jGmyeNpCu2VpIwH5aZmPv5UE?fife=s16383", latitude: -20.2617493, longitude: 57.4824836)
Station.create(name: "Trianon Station", image_url: "https://doc-0s-04-mymaps.googleusercontent.com/untrusted/hostedimage/ou6c6r4ot251igcmt16atv0meo/neb0b1nqp4d8re7d60fndtcfm0/1663069500000/lU_O4jlGNaHVZq3aQyWXZYVjF9e8lyDa/*/6AFzc1vYtwBFYs4kKSz48kazaXcuHEUNXuV3B4XNSspUcHQROPYw2ay5pnluy3qWpfEtWnW9GrrUYT9DB1KcNhDUObDQgBLwoBw1hs-dRyR4IKjPYh1AVSBbe_ZXTS9iDQW3W9BlcFBwCHMBYax31aCDhSdkmTfNCFr0976y81Wn309NCGdWKMb5_uksj7aivZB2FIP9a?fife=s16383", latitude: -20.2610855, longitude: 57.489833)
Station.create(name: "Phoenix Station", image_url: "https://doc-0c-04-mymaps.googleusercontent.com/untrusted/hostedimage/ou6c6r4ot251igcmt16atv0meo/isk3bmvd20ebbts98e9pjh5dl4/1663069500000/lU_O4jlGNaHVZq3aQyWXZYVjF9e8lyDa/*/6AFzc1vZUteb8Isl8cUnZgeoSn9qjAKoZXwbt2jxgMPlf3oEzJZDwoq7ZZdU6x7uOFO9yCLHJlsYWklQRevaFNhjbMS2rb2X9IbT9HZ7PJuQH_O7yJ-OxdbcxvlMyP7Ch0zUxcY2RccLuexR0pjnUMshgVVjaaKQrRCncjPTUEWL05sQjWvZTC8WUvOwf6W7FrPE144Ax?fife=s16383", latitude: -20.275049, longitude: 57.4965487)
Station.create(name: "Phoenix Mall Station", image_url: "https://doc-00-04-mymaps.googleusercontent.com/untrusted/hostedimage/ou6c6r4ot251igcmt16atv0meo/a61obb0o1ej2irdkhccll8m6so/1663069500000/lU_O4jlGNaHVZq3aQyWXZYVjF9e8lyDa/*/6AFzc1vafYXJbS8x1vm2Oje_8fPRdSWDjNLyOSyU6b-Sfl9qoiPkoTJvcnD7blcYBTQQJG9apH2HuR6-zBpm_K2z6ROAQ1w4gIOSYG0ZaOEBuaPXxnwIZKhYTtOWqlF-zuNoX9d3BCe4SLeinMMmUDeLIvfQkrlYQkorG3woAooREx4BBKW7698vjH6F0iZkyRz8vBbey?fife=s16383", latitude: -20.2797464, longitude: 57.4971339)
Station.create(name: "Palmerston Station", image_url: "https://doc-10-04-mymaps.googleusercontent.com/untrusted/hostedimage/ou6c6r4ot251igcmt16atv0meo/6tf8h1s600c44be7ue7gdlh5n0/1663069500000/lU_O4jlGNaHVZq3aQyWXZYVjF9e8lyDa/*/6AFzc1vbKFG4WvKm1tkFxLqMr1UzFKJ3IHSO5yailHEEZ_YmkiTvMlw7degtVp-HIkTRmtYOdAECeud2AbONxDcc5DrX-kJLrfWscHFmmHgdacXcVUAp4JkTBzpQFPmaC5Ds_Nfd4BVehnyJDNNiW1GZhMbAUFl5JX5vNMjkrY-r55T6MH19pGeDQXe9-zaLE1jDKfkdE?fife=s16383", latitude: -20.2850436, longitude: 57.4973445)
Station.create(name: "Vacoas Central", image_url: "https://doc-0s-04-mymaps.googleusercontent.com/untrusted/hostedimage/ou6c6r4ot251igcmt16atv0meo/g0f0r81hgh5abrn7tn4mtp5ubg/1663069500000/lU_O4jlGNaHVZq3aQyWXZYVjF9e8lyDa/*/6AFzc1vaR7-jE0ao_KUUd6UPIH-Tuk2jHZy4uvXkLw_ktInrndrxontTDkUUWeZG1bzEhb3A7_NNtasOo54vBmQW5orQL4_DSufyqyCQU_3kRUeSB1DOFLd6Tuy64hbdq8oQWKooG1RzrMMgeOV7uBWH_IMXHUVqMD5PWBCFAVyW99Nr7CtprTXkApmC1DKYAADoxixAC?fife=s16383", latitude: -20.2950453, longitude: 57.4933938)
Station.create(name: "Sadally Station", image_url: "https://doc-0s-04-mymaps.googleusercontent.com/untrusted/hostedimage/ou6c6r4ot251igcmt16atv0meo/k5gpk013vvj4ofpn5v58h6dfa0/1663069500000/lU_O4jlGNaHVZq3aQyWXZYVjF9e8lyDa/*/6AFzc1vZ2t2s1CimjESXZn-3GXCf-STj2QGDQUWWECYRGmMazeEcn_5RG4h-dZSLi_5ppjZNAyNuHnPALfSWbpiDI9X8gUm5H5zWJlMCoDc11bjE4qAFkHfGIQE4I7q-wiw_2lqMJxsO7g7uP6IaC7Yxaf50Z58rufgxahK5nASLh8dTck_VMWevp-ZFt2W6Jmng1gPZz?fife=s16383", latitude: -20.3018021, longitude: 57.4958665)
Station.create(name: "Floreal Station", image_url: "https://doc-08-04-mymaps.googleusercontent.com/untrusted/hostedimage/ou6c6r4ot251igcmt16atv0meo/ap23epo2rj7m36o1i3i0lld3ic/1663069500000/lU_O4jlGNaHVZq3aQyWXZYVjF9e8lyDa/*/6AFzc1vZRvt091v50f-pXENaBJGf5EmBubmNmxZzzY1b6kXqMYpQuM9Ixh_UGhSZiIaOdZ6NVnAkaXWUgxcPeX5InnTQaNxVDJ2COyXP1PF1rMWW4GFh8nGZUf1eLSQEcmieTB-2Tj7V3aTA9ZybMsLAxgPY-HM5lsXk3QsJfuooKrqq-pIeaBi8TMQPsWHn7k8uP_TdQ?fife=s16383", latitude: -20.3073556, longitude: 57.5072335)
Station.create(name: "Curepipe Central", image_url: "https://doc-04-04-mymaps.googleusercontent.com/untrusted/hostedimage/ou6c6r4ot251igcmt16atv0meo/7n25fk2dl8g99jnkkir2kpqqg0/1663069500000/lU_O4jlGNaHVZq3aQyWXZYVjF9e8lyDa/*/6AFzc1vb06u9FDOWk1pqhVAzVuDGHVr46HOH7HEpDJfDvCm08RkotlXttcrM8aJ77j-IXw7ClokS3WvykjE8rr6BmKxLn2jlSVyqOsNU1hSuQngqEjbZqINXfr9p3jZB5Tl2J9m5RmxeZUh9Ge-F3e3yrmhzRG461FSavV_LVYBM1BIuRLQXfBLcEwcV7nYePvwQDeQ7v?fife=s16383", latitude: -20.3163468, longitude: 57.5254854)

Itinerary.create(origin: "Port Louis Victoria Central", destination: "St Louis Station", price: 47, duration: 2)
Itinerary.create(origin: "Port Louis Victoria Central", destination: "Coromandel Station", price: 47, duration: 2)
Itinerary.create(origin: "Port Louis Victoria Central", destination: "Barkly Station", price: 38, duration: 4)
Itinerary.create(origin: "Port Louis Victoria Central", destination: "Beau Bassin Station", price: 38, duration: 5)
Itinerary.create(origin: "Port Louis Victoria Central", destination: "Vandermeersch Station", price: 32, duration: 4)
Itinerary.create(origin: "Port Louis Victoria Central", destination: "Rose-Hill Central", price: 32, duration: 3)
Itinerary.create(origin: "Port Louis Victoria Central", destination: "Belle Rose Station", price: 32, duration: 9)
Itinerary.create(origin: "Port Louis Victoria Central", destination: "Quatre Bornes Central", price: 32, duration: 12)
Itinerary.create(origin: "Port Louis Victoria Central", destination: "St Jean Station", price: 32, duration: 11)
Itinerary.create(origin: "Port Louis Victoria Central", destination: "Trianon Station", price: 32, duration: 15)
Itinerary.create(origin: "Port Louis Victoria Central", destination: "Phoenix Station", price: 32, duration: 18)
Itinerary.create(origin: "Port Louis Victoria Central", destination: "Phoenix Mall Station", price: 32, duration: 17)
Itinerary.create(origin: "Port Louis Victoria Central", destination: "Palmerston Station", price: 32, duration: 17)
Itinerary.create(origin: "Port Louis Victoria Central", destination: "Vacoas Central", price: 32, duration: 16)
Itinerary.create(origin: "Port Louis Victoria Central", destination: "Sadally Station", price: 32, duration: 16)
Itinerary.create(origin: "Port Louis Victoria Central", destination: "Floreal Station", price: 32, duration: 9)
Itinerary.create(origin: "Port Louis Victoria Central", destination: "Curepipe Central", price: 32, duration: 10)

Itinerary.create(origin: "St Louis Station", destination: "Port Louis Victoria Central", price: 47, duration: 2)
Itinerary.create(origin: "St Louis Station", destination: "Coromandel Station", price: 47, duration: 2)
Itinerary.create(origin: "St Louis Station", destination: "Barkly Station", price: 38, duration: 7)
Itinerary.create(origin: "St Louis Station", destination: "Beau Bassin Station", price: 32, duration: 10)
Itinerary.create(origin: "St Louis Station", destination: "Vandermeersch Station", price: 32, duration: 10)
Itinerary.create(origin: "St Louis Station", destination: "Rose-Hill Central", price: 32, duration: 12)
Itinerary.create(origin: "St Louis Station", destination: "Belle Rose Station", price: 32, duration: 13)
Itinerary.create(origin: "St Louis Station", destination: "Quatre Bornes Central", price: 32, duration: 12)
Itinerary.create(origin: "St Louis Station", destination: "St Jean Station", price: 32, duration: 11)
Itinerary.create(origin: "St Louis Station", destination: "Trianon Station", price: 32, duration: 14)
Itinerary.create(origin: "St Louis Station", destination: "Phoenix Station", price: 32, duration: 16)
Itinerary.create(origin: "St Louis Station", destination: "Phoenix Mall Station", price: 32, duration: 16)
Itinerary.create(origin: "St Louis Station", destination: "Palmerston Station", price: 32, duration: 13)
Itinerary.create(origin: "St Louis Station", destination: "Vacoas Central", price: 32, duration: 11)
Itinerary.create(origin: "St Louis Station", destination: "Sadally Station", price: 32, duration: 11)
Itinerary.create(origin: "St Louis Station", destination: "Floreal Station", price: 32, duration: 14)
Itinerary.create(origin: "St Louis Station", destination: "Curepipe Central", price: 32, duration: 15)

Itinerary.create(origin: "Coromandel Station", destination: "Port Louis Victoria Central", price: 47, duration: 2)
Itinerary.create(origin: "Coromandel Station", destination: "St Louis Station", price: 47, duration: 2)
Itinerary.create(origin: "Coromandel Station", destination: "Barkly Station", price: 38, duration: 7)
Itinerary.create(origin: "Coromandel Station", destination: "Beau Bassin Station", price: 32, duration: 10)
Itinerary.create(origin: "Coromandel Station", destination: "Vandermeersch Station", price: 32, duration: 4)
Itinerary.create(origin: "Coromandel Station", destination: "Rose-Hill Central", price: 32, duration: 10)
Itinerary.create(origin: "Coromandel Station", destination: "Belle Rose Station", price: 32, duration: 11)
Itinerary.create(origin: "Coromandel Station", destination: "Quatre Bornes Central", price: 32, duration: 12)
Itinerary.create(origin: "Coromandel Station", destination: "St Jean Station", price: 32, duration: 10)
Itinerary.create(origin: "Coromandel Station", destination: "Trianon Station", price: 32, duration: 10)
Itinerary.create(origin: "Coromandel Station", destination: "Phoenix Station", price: 32, duration: 12)
Itinerary.create(origin: "Coromandel Station", destination: "Phoenix Mall Station", price: 32, duration: 12)
Itinerary.create(origin: "Coromandel Station", destination: "Palmerston Station", price: 32, duration: 6)
Itinerary.create(origin: "Coromandel Station", destination: "Vacoas Central", price: 32, duration: 8)
Itinerary.create(origin: "Coromandel Station", destination: "Sadally Station", price: 32, duration: 8)
Itinerary.create(origin: "Coromandel Station", destination: "Floreal Station", price: 32, duration: 15)
Itinerary.create(origin: "Coromandel Station", destination: "Curepipe Central", price: 32, duration: 16)

Itinerary.create(origin: "Barkly Station", destination: "Port Louis Victoria Central", price: 47, duration: 7)
Itinerary.create(origin: "Barkly Station", destination: "St Louis Station", price: 47, duration: 6)
Itinerary.create(origin: "Barkly Station", destination: "Coromandel Station", price: 47, duration: 3)
Itinerary.create(origin: "Barkly Station", destination: "Beau Bassin Station", price: 32, duration: 2)
Itinerary.create(origin: "Barkly Station", destination: "Vandermeersch Station", price: 32, duration: 2)
Itinerary.create(origin: "Barkly Station", destination: "Rose-Hill Central", price: 32, duration: 4)
Itinerary.create(origin: "Barkly Station", destination: "Belle Rose Station", price: 32, duration: 5)
Itinerary.create(origin: "Barkly Station", destination: "Quatre Bornes Central", price: 32, duration: 6)
Itinerary.create(origin: "Barkly Station", destination: "St Jean Station", price: 32, duration: 7)
Itinerary.create(origin: "Barkly Station", destination: "Trianon Station", price: 32, duration: 9)
Itinerary.create(origin: "Barkly Station", destination: "Phoenix Station", price: 32, duration: 10)
Itinerary.create(origin: "Barkly Station", destination: "Phoenix Mall Station", price: 32, duration: 10)
Itinerary.create(origin: "Barkly Station", destination: "Palmerston Station", price: 32, duration: 4)
Itinerary.create(origin: "Barkly Station", destination: "Vacoas Central", price: 32, duration: 3)
Itinerary.create(origin: "Barkly Station", destination: "Sadally Station", price: 32, duration: 3)
Itinerary.create(origin: "Barkly Station", destination: "Floreal Station", price: 32, duration: 9)
Itinerary.create(origin: "Barkly Station", destination: "Curepipe Central", price: 32, duration: 10)

Itinerary.create(origin: "Beau Bassin Station", destination: "Port Louis Victoria Central", price: 47, duration: 7)
Itinerary.create(origin: "Beau Bassin Station", destination: "St Louis Station", price: 47, duration: 6)
Itinerary.create(origin: "Beau Bassin Station", destination: "Coromandel Station", price: 47, duration: 3)
Itinerary.create(origin: "Beau Bassin Station", destination: "Barkly Station", price: 38, duration: 2)
Itinerary.create(origin: "Beau Bassin Station", destination: "Vandermeersch Station", price: 32, duration: 2)
Itinerary.create(origin: "Beau Bassin Station", destination: "Rose-Hill Central", price: 32, duration: 4)
Itinerary.create(origin: "Beau Bassin Station", destination: "Belle Rose Station", price: 32, duration: 5)
Itinerary.create(origin: "Beau Bassin Station", destination: "Quatre Bornes Central", price: 32, duration: 6)
Itinerary.create(origin: "Beau Bassin Station", destination: "St Jean Station", price: 32, duration: 7)
Itinerary.create(origin: "Beau Bassin Station", destination: "Trianon Station", price: 32, duration: 9)
Itinerary.create(origin: "Beau Bassin Station", destination: "Phoenix Station", price: 32, duration: 10)
Itinerary.create(origin: "Beau Bassin Station", destination: "Phoenix Mall Station", price: 32, duration: 10)
Itinerary.create(origin: "Beau Bassin Station", destination: "Palmerston Station", price: 32, duration: 4)
Itinerary.create(origin: "Beau Bassin Station", destination: "Vacoas Central", price: 32, duration: 3)
Itinerary.create(origin: "Beau Bassin Station", destination: "Sadally Station", price: 32, duration: 3)
Itinerary.create(origin: "Beau Bassin Station", destination: "Floreal Station", price: 32, duration: 9)
Itinerary.create(origin: "Beau Bassin Station", destination: "Curepipe Central", price: 32, duration: 10)

Itinerary.create(origin: "Vandermeersch Station", destination: "Port Louis Victoria Central", price: 47, duration: 7)
Itinerary.create(origin: "Vandermeersch Station", destination: "St Louis Station", price: 47, duration: 6)
Itinerary.create(origin: "Vandermeersch Station", destination: "Coromandel Station", price: 47, duration: 3)
Itinerary.create(origin: "Vandermeersch Station", destination: "Barkly Station", price: 38, duration: 2)
Itinerary.create(origin: "Vandermeersch Station", destination: "Beau Bassin Station", price: 32, duration: 2)
Itinerary.create(origin: "Vandermeersch Station", destination: "Rose-Hill Central", price: 32, duration: 4)
Itinerary.create(origin: "Vandermeersch Station", destination: "Belle Rose Station", price: 32, duration: 5)
Itinerary.create(origin: "Vandermeersch Station", destination: "Quatre Bornes Central", price: 32, duration: 6)
Itinerary.create(origin: "Vandermeersch Station", destination: "St Jean Station", price: 32, duration: 7)
Itinerary.create(origin: "Vandermeersch Station", destination: "Trianon Station", price: 32, duration: 9)
Itinerary.create(origin: "Vandermeersch Station", destination: "Phoenix Station", price: 32, duration: 10)
Itinerary.create(origin: "Vandermeersch Station", destination: "Phoenix Mall Station", price: 32, duration: 10)
Itinerary.create(origin: "Vandermeersch Station", destination: "Palmerston Station", price: 32, duration: 4)
Itinerary.create(origin: "Vandermeersch Station", destination: "Vacoas Central", price: 32, duration: 3)
Itinerary.create(origin: "Vandermeersch Station", destination: "Sadally Station", price: 32, duration: 3)
Itinerary.create(origin: "Vandermeersch Station", destination: "Floreal Station", price: 32, duration: 9)
Itinerary.create(origin: "Vandermeersch Station", destination: "Curepipe Central", price: 32, duration: 10)

Itinerary.create(origin: "Rose-Hill Central", destination: "Port Louis Victoria Central", price: 47, duration: 8)
Itinerary.create(origin: "Rose-Hill Central", destination: "St Louis Station", price: 47, duration: 7)
Itinerary.create(origin: "Rose-Hill Central", destination: "Coromandel Station", price: 47, duration: 5)
Itinerary.create(origin: "Rose-Hill Central", destination: "Barkly Station", price: 38, duration: 2)
Itinerary.create(origin: "Rose-Hill Central", destination: "Beau Bassin Station", price: 32, duration: 4)
Itinerary.create(origin: "Rose-Hill Central", destination: "Vandermeersch Station", price: 32, duration: 3)
Itinerary.create(origin: "Rose-Hill Central", destination: "Belle Rose Station", price: 32, duration: 2)
Itinerary.create(origin: "Rose-Hill Central", destination: "Quatre Bornes Central", price: 32, duration: 5)
Itinerary.create(origin: "Rose-Hill Central", destination: "St Jean Station", price: 32, duration: 5)
Itinerary.create(origin: "Rose-Hill Central", destination: "Trianon Station", price: 32, duration: 15)
Itinerary.create(origin: "Rose-Hill Central", destination: "Phoenix Station", price: 32, duration: 16)
Itinerary.create(origin: "Rose-Hill Central", destination: "Phoenix Mall Station", price: 32, duration: 16)
Itinerary.create(origin: "Rose-Hill Central", destination: "Palmerston Station", price: 32, duration: 4)
Itinerary.create(origin: "Rose-Hill Central", destination: "Vacoas Central", price: 32, duration: 2)
Itinerary.create(origin: "Rose-Hill Central", destination: "Sadally Station", price: 32, duration: 2)
Itinerary.create(origin: "Rose-Hill Central", destination: "Floreal Station", price: 32, duration: 6)
Itinerary.create(origin: "Rose-Hill Central", destination: "Curepipe Central", price: 32, duration: 7)

Itinerary.create(origin: "Belle Rose Station", destination: "Port Louis Victoria Central", price: 47, duration: 8)
Itinerary.create(origin: "Belle Rose Station", destination: "St Louis Station", price: 47, duration: 7)
Itinerary.create(origin: "Belle Rose Station", destination: "Coromandel Station", price: 47, duration: 5)
Itinerary.create(origin: "Belle Rose Station", destination: "Barkly Station", price: 38, duration: 2)
Itinerary.create(origin: "Belle Rose Station", destination: "Beau Bassin Station", price: 32, duration: 4)
Itinerary.create(origin: "Belle Rose Station", destination: "Vandermeersch Station", price: 32, duration: 3)
Itinerary.create(origin: "Belle Rose Station", destination: "Rose-Hill Central", price: 32, duration: 2)
Itinerary.create(origin: "Belle Rose Station", destination: "Quatre Bornes Central", price: 32, duration: 5)
Itinerary.create(origin: "Belle Rose Station", destination: "St Jean Station", price: 32, duration: 5)
Itinerary.create(origin: "Belle Rose Station", destination: "Trianon Station", price: 32, duration: 15)
Itinerary.create(origin: "Belle Rose Station", destination: "Phoenix Station", price: 32, duration: 16)
Itinerary.create(origin: "Belle Rose Station", destination: "Phoenix Mall Station", price: 32, duration: 16)
Itinerary.create(origin: "Belle Rose Station", destination: "Palmerston Station", price: 32, duration: 4)
Itinerary.create(origin: "Belle Rose Station", destination: "Vacoas Central", price: 32, duration: 2)
Itinerary.create(origin: "Belle Rose Station", destination: "Sadally Station", price: 32, duration: 2)
Itinerary.create(origin: "Belle Rose Station", destination: "Floreal Station", price: 32, duration: 6)
Itinerary.create(origin: "Belle Rose Station", destination: "Curepipe Central", price: 32, duration: 6)

Itinerary.create(origin: "Quatre Bornes Central", destination: "Port Louis Victoria Central", price: 47, duration: 10)
Itinerary.create(origin: "Quatre Bornes Central", destination: "St Louis Station", price: 47, duration: 9)
Itinerary.create(origin: "Quatre Bornes Central", destination: "Coromandel Station", price: 47, duration: 6)
Itinerary.create(origin: "Quatre Bornes Central", destination: "Barkly Station", price: 38, duration: 5)
Itinerary.create(origin: "Quatre Bornes Central", destination: "Beau Bassin Station", price: 32, duration: 5)
Itinerary.create(origin: "Quatre Bornes Central", destination: "Vandermeersch Station", price: 32, duration: 5)
Itinerary.create(origin: "Quatre Bornes Central", destination: "Rose-Hill Central", price: 32, duration: 5)
Itinerary.create(origin: "Quatre Bornes Central", destination: "Belle Rose Station", price: 32, duration: 5)
Itinerary.create(origin: "Quatre Bornes Central", destination: "St Jean Station", price: 32, duration: 1)
Itinerary.create(origin: "Quatre Bornes Central", destination: "Trianon Station", price: 32, duration: 2)
Itinerary.create(origin: "Quatre Bornes Central", destination: "Phoenix Station", price: 32, duration: 5)
Itinerary.create(origin: "Quatre Bornes Central", destination: "Phoenix Mall Station", price: 32, duration: 5)
Itinerary.create(origin: "Quatre Bornes Central", destination: "Palmerston Station", price: 32, duration: 3)
Itinerary.create(origin: "Quatre Bornes Central", destination: "Vacoas Central", price: 32, duration: 3)
Itinerary.create(origin: "Quatre Bornes Central", destination: "Sadally Station", price: 32, duration: 3)
Itinerary.create(origin: "Quatre Bornes Central", destination: "Floreal Station", price: 32, duration: 10)
Itinerary.create(origin: "Quatre Bornes Central", destination: "Curepipe Central", price: 32, duration: 11)

Itinerary.create(origin: "St Jean Station", destination: "Port Louis Victoria Central", price: 47, duration: 10)
Itinerary.create(origin: "St Jean Station", destination: "St Louis Station", price: 47, duration: 9)
Itinerary.create(origin: "St Jean Station", destination: "Coromandel Station", price: 47, duration: 6)
Itinerary.create(origin: "St Jean Station", destination: "Barkly Station", price: 38, duration: 5)
Itinerary.create(origin: "St Jean Station", destination: "Beau Bassin Station", price: 32, duration: 5)
Itinerary.create(origin: "St Jean Station", destination: "Vandermeersch Station", price: 32, duration: 5)
Itinerary.create(origin: "St Jean Station", destination: "Rose-Hill Central", price: 32, duration: 5)
Itinerary.create(origin: "St Jean Station", destination: "Belle Rose Station", price: 32, duration: 5)
Itinerary.create(origin: "St Jean Station", destination: "Quatre Bornes Central", price: 32, duration: 1)
Itinerary.create(origin: "St Jean Station", destination: "Trianon Station", price: 32, duration: 2)
Itinerary.create(origin: "St Jean Station", destination: "Phoenix Station", price: 32, duration: 5)
Itinerary.create(origin: "St Jean Station", destination: "Phoenix Mall Station", price: 32, duration: 5)
Itinerary.create(origin: "St Jean Station", destination: "Palmerston Station", price: 32, duration: 3)
Itinerary.create(origin: "St Jean Station", destination: "Vacoas Central", price: 32, duration: 3)
Itinerary.create(origin: "St Jean Station", destination: "Sadally Station", price: 32, duration: 3)
Itinerary.create(origin: "St Jean Station", destination: "Floreal Station", price: 32, duration: 10)
Itinerary.create(origin: "St Jean Station", destination: "Curepipe Central", price: 32, duration: 11)

Itinerary.create(origin: "Trianon Station", destination: "Port Louis Victoria Central", price: 47, duration: 15)
Itinerary.create(origin: "Trianon Station", destination: "St Louis Station", price: 47, duration: 13)
Itinerary.create(origin: "Trianon Station", destination: "Coromandel Station", price: 47, duration: 11)
Itinerary.create(origin: "Trianon Station", destination: "Barkly Station", price: 38, duration: 7)
Itinerary.create(origin: "Trianon Station", destination: "Beau Bassin Station", price: 32, duration: 7)
Itinerary.create(origin: "Trianon Station", destination: "Vandermeersch Station", price: 32, duration: 7)
Itinerary.create(origin: "Trianon Station", destination: "Rose-Hill Central", price: 32, duration: 7)
Itinerary.create(origin: "Trianon Station", destination: "Belle Rose Station", price: 32, duration: 7)
Itinerary.create(origin: "Trianon Station", destination: "Quatre Bornes Central", price: 32, duration: 2)
Itinerary.create(origin: "Trianon Station", destination: "St Jean Station", price: 32, duration: 2)
Itinerary.create(origin: "Trianon Station", destination: "Phoenix Station", price: 32, duration: 5)
Itinerary.create(origin: "Trianon Station", destination: "Phoenix Mall Station", price: 32, duration: 5)
Itinerary.create(origin: "Trianon Station", destination: "Palmerston Station", price: 32, duration: 7)
Itinerary.create(origin: "Trianon Station", destination: "Vacoas Central", price: 32, duration: 9)
Itinerary.create(origin: "Trianon Station", destination: "Sadally Station", price: 32, duration: 9)
Itinerary.create(origin: "Trianon Station", destination: "Floreal Station", price: 32, duration: 13)
Itinerary.create(origin: "Trianon Station", destination: "Curepipe Central", price: 32, duration: 15)

Itinerary.create(origin: "Phoenix Station", destination: "Port Louis Victoria Central", price: 47, duration: 15)
Itinerary.create(origin: "Phoenix Station", destination: "St Louis Station", price: 47, duration: 15)
Itinerary.create(origin: "Phoenix Station", destination: "Coromandel Station", price: 47, duration: 12)
Itinerary.create(origin: "Phoenix Station", destination: "Barkly Station", price: 38, duration: 8)
Itinerary.create(origin: "Phoenix Station", destination: "Beau Bassin Station", price: 32, duration: 8)
Itinerary.create(origin: "Phoenix Station", destination: "Vandermeersch Station", price: 32, duration: 8)
Itinerary.create(origin: "Phoenix Station", destination: "Rose-Hill Central", price: 32, duration: 8)
Itinerary.create(origin: "Phoenix Station", destination: "Belle Rose Station", price: 32, duration: 8)
Itinerary.create(origin: "Phoenix Station", destination: "Quatre Bornes Central", price: 32, duration: 5)
Itinerary.create(origin: "Phoenix Station", destination: "St Jean Station", price: 32, duration: 5)
Itinerary.create(origin: "Phoenix Station", destination: "Trianon Station", price: 32, duration: 5)
Itinerary.create(origin: "Phoenix Station", destination: "Phoenix Mall Station", price: 32, duration: 1)
Itinerary.create(origin: "Phoenix Station", destination: "Palmerston Station", price: 32, duration: 8)
Itinerary.create(origin: "Phoenix Station", destination: "Vacoas Central", price: 32, duration: 8)
Itinerary.create(origin: "Phoenix Station", destination: "Sadally Station", price: 32, duration: 8)
Itinerary.create(origin: "Phoenix Station", destination: "Floreal Station", price: 32, duration: 7)
Itinerary.create(origin: "Phoenix Station", destination: "Curepipe Central", price: 32, duration: 8)

Itinerary.create(origin: "Phoenix Mall Station", destination: "Port Louis Victoria Central", price: 47, duration: 15)
Itinerary.create(origin: "Phoenix Mall Station", destination: "St Louis Station", price: 47, duration: 15)
Itinerary.create(origin: "Phoenix Mall Station", destination: "Coromandel Station", price: 47, duration: 12)
Itinerary.create(origin: "Phoenix Mall Station", destination: "Barkly Station", price: 38, duration: 8)
Itinerary.create(origin: "Phoenix Mall Station", destination: "Beau Bassin Station", price: 32, duration: 8)
Itinerary.create(origin: "Phoenix Mall Station", destination: "Vandermeersch Station", price: 32, duration: 8)
Itinerary.create(origin: "Phoenix Mall Station", destination: "Rose-Hill Central", price: 32, duration: 8)
Itinerary.create(origin: "Phoenix Mall Station", destination: "Belle Rose Station", price: 32, duration: 8)
Itinerary.create(origin: "Phoenix Mall Station", destination: "Quatre Bornes Central", price: 32, duration: 5)
Itinerary.create(origin: "Phoenix Mall Station", destination: "St Jean Station", price: 32, duration: 5)
Itinerary.create(origin: "Phoenix Mall Station", destination: "Trianon Station", price: 32, duration: 5)
Itinerary.create(origin: "Phoenix Mall Station", destination: "Phoenix Station", price: 32, duration: 1)
Itinerary.create(origin: "Phoenix Mall Station", destination: "Palmerston Station", price: 32, duration: 8)
Itinerary.create(origin: "Phoenix Mall Station", destination: "Vacoas Central", price: 32, duration: 8)
Itinerary.create(origin: "Phoenix Mall Station", destination: "Sadally Station", price: 32, duration: 8)
Itinerary.create(origin: "Phoenix Mall Station", destination: "Floreal Station", price: 32, duration: 7)
Itinerary.create(origin: "Phoenix Mall Station", destination: "Curepipe Central", price: 32, duration: 8)

Itinerary.create(origin: "Palmerston Station", destination: "Port Louis Victoria Central", price: 47, duration: 7)
Itinerary.create(origin: "Palmerston Station", destination: "St Louis Station", price: 47, duration: 6)
Itinerary.create(origin: "Palmerston Station", destination: "Coromandel Station", price: 47, duration: 3)
Itinerary.create(origin: "Palmerston Station", destination: "Barkly Station", price: 38, duration: 2)
Itinerary.create(origin: "Palmerston Station", destination: "Beau Bassin Station", price: 32, duration: 2)
Itinerary.create(origin: "Palmerston Station", destination: "Vandermeersch Station", price: 32, duration: 4)
Itinerary.create(origin: "Palmerston Station", destination: "Rose-Hill Central", price: 32, duration: 4)
Itinerary.create(origin: "Palmerston Station", destination: "Belle Rose Station", price: 32, duration: 5)
Itinerary.create(origin: "Palmerston Station", destination: "Quatre Bornes Central", price: 32, duration: 6)
Itinerary.create(origin: "Palmerston Station", destination: "St Jean Station", price: 32, duration: 6)
Itinerary.create(origin: "Palmerston Station", destination: "Trianon Station", price: 32, duration: 9)
Itinerary.create(origin: "Palmerston Station", destination: "Phoenix Station", price: 32, duration: 10)
Itinerary.create(origin: "Palmerston Station", destination: "Phoenix Mall Station", price: 32, duration: 10)
Itinerary.create(origin: "Palmerston Station", destination: "Vacoas Central", price: 32, duration: 3)
Itinerary.create(origin: "Palmerston Station", destination: "Sadally Station", price: 32, duration: 3)
Itinerary.create(origin: "Palmerston Station", destination: "Floreal Station", price: 32, duration: 9)
Itinerary.create(origin: "Palmerston Station", destination: "Curepipe Central", price: 32, duration: 10)

Itinerary.create(origin: "Vacoas Central", destination: "Port Louis Victoria Central", price: 47, duration: 10)
Itinerary.create(origin: "Vacoas Central", destination: "St Louis Station", price: 47, duration: 9)
Itinerary.create(origin: "Vacoas Central", destination: "Coromandel Station", price: 47, duration: 7)
Itinerary.create(origin: "Vacoas Central", destination: "Barkly Station", price: 38, duration: 3)
Itinerary.create(origin: "Vacoas Central", destination: "Beau Bassin Station", price: 32, duration: 3)
Itinerary.create(origin: "Vacoas Central", destination: "Vandermeersch Station", price: 32, duration: 3)
Itinerary.create(origin: "Vacoas Central", destination: "Rose-Hill Central", price: 32, duration: 3)
Itinerary.create(origin: "Vacoas Central", destination: "Belle Rose Station", price: 32, duration: 3)
Itinerary.create(origin: "Vacoas Central", destination: "Quatre Bornes Central", price: 32, duration: 6)
Itinerary.create(origin: "Vacoas Central", destination: "St Jean Station", price: 32, duration: 6)
Itinerary.create(origin: "Vacoas Central", destination: "Trianon Station", price: 32, duration: 8)
Itinerary.create(origin: "Vacoas Central", destination: "Phoenix Station", price: 32, duration: 10)
Itinerary.create(origin: "Vacoas Central", destination: "Phoenix Mall Station", price: 32, duration: 10)
Itinerary.create(origin: "Vacoas Central", destination: "Palmerston Station", price: 32, duration: 3)
Itinerary.create(origin: "Vacoas Central", destination: "Sadally Station", price: 32, duration: 1)
Itinerary.create(origin: "Vacoas Central", destination: "Floreal Station", price: 32, duration: 9)
Itinerary.create(origin: "Vacoas Central", destination: "Curepipe Central", price: 32, duration: 10)

Itinerary.create(origin: "Sadally Station", destination: "Port Louis Victoria Central", price: 47, duration: 10)
Itinerary.create(origin: "Sadally Station", destination: "St Louis Station", price: 47, duration: 9)
Itinerary.create(origin: "Sadally Station", destination: "Coromandel Station", price: 47, duration: 7)
Itinerary.create(origin: "Sadally Station", destination: "Barkly Station", price: 38, duration: 3)
Itinerary.create(origin: "Sadally Station", destination: "Beau Bassin Station", price: 32, duration: 3)
Itinerary.create(origin: "Sadally Station", destination: "Vandermeersch Station", price: 32, duration: 3)
Itinerary.create(origin: "Sadally Station", destination: "Rose-Hill Central", price: 32, duration: 3)
Itinerary.create(origin: "Sadally Station", destination: "Belle Rose Station", price: 32, duration: 6)
Itinerary.create(origin: "Sadally Station", destination: "Quatre Bornes Central", price: 32, duration: 6)
Itinerary.create(origin: "Sadally Station", destination: "St Jean Station", price: 32, duration: 6)
Itinerary.create(origin: "Sadally Station", destination: "Trianon Station", price: 32, duration: 8)
Itinerary.create(origin: "Sadally Station", destination: "Phoenix Station", price: 32, duration: 10)
Itinerary.create(origin: "Sadally Station", destination: "Phoenix Mall Station", price: 32, duration: 10)
Itinerary.create(origin: "Sadally Station", destination: "Palmerston Station", price: 32, duration: 3)
Itinerary.create(origin: "Sadally Station", destination: "Vacoas Central", price: 32, duration: 1)
Itinerary.create(origin: "Sadally Station", destination: "Floreal Station", price: 32, duration: 9)
Itinerary.create(origin: "Sadally Station", destination: "Curepipe Central", price: 32, duration: 10)

Itinerary.create(origin: "Floreal Station", destination: "Port Louis Victoria Central", price: 47, duration: 20)
Itinerary.create(origin: "Floreal Station", destination: "St Louis Station", price: 47, duration: 20)
Itinerary.create(origin: "Floreal Station", destination: "Coromandel Station", price: 47, duration: 20)
Itinerary.create(origin: "Floreal Station", destination: "Barkly Station", price: 38, duration: 10)
Itinerary.create(origin: "Floreal Station", destination: "Beau Bassin Station", price: 32, duration: 10)
Itinerary.create(origin: "Floreal Station", destination: "Vandermeersch Station", price: 32, duration: 10)
Itinerary.create(origin: "Floreal Station", destination: "Rose-Hill Central", price: 32, duration: 10)
Itinerary.create(origin: "Floreal Station", destination: "Belle Rose Station", price: 32, duration: 10)
Itinerary.create(origin: "Floreal Station", destination: "Quatre Bornes Central", price: 32, duration: 10)
Itinerary.create(origin: "Floreal Station", destination: "St Jean Station", price: 32, duration: 11)
Itinerary.create(origin: "Floreal Station", destination: "Trianon Station", price: 32, duration: 15)
Itinerary.create(origin: "Floreal Station", destination: "Phoenix Station", price: 32, duration: 16)
Itinerary.create(origin: "Floreal Station", destination: "Phoenix Mall Station", price: 32, duration: 16)
Itinerary.create(origin: "Floreal Station", destination: "Palmerston Station", price: 32, duration: 5)
Itinerary.create(origin: "Floreal Station", destination: "Vacoas Central", price: 32, duration: 6)
Itinerary.create(origin: "Floreal Station", destination: "Sadally Station", price: 32, duration: 7)
Itinerary.create(origin: "Floreal Station", destination: "Curepipe Central", price: 32, duration: 2)

Itinerary.create(origin: "Curepipe Central", destination: "Port Louis Victoria Central", price: 47, duration: 20)
Itinerary.create(origin: "Curepipe Central", destination: "St Louis Station", price: 47, duration: 20)
Itinerary.create(origin: "Curepipe Central", destination: "Coromandel Station", price: 47, duration: 20)
Itinerary.create(origin: "Curepipe Central", destination: "Barkly Station", price: 38, duration: 10)
Itinerary.create(origin: "Curepipe Central", destination: "Beau Bassin Station", price: 32, duration: 10)
Itinerary.create(origin: "Curepipe Central", destination: "Vandermeersch Station", price: 32, duration: 10)
Itinerary.create(origin: "Curepipe Central", destination: "Rose-Hill Central", price: 32, duration: 10)
Itinerary.create(origin: "Curepipe Central", destination: "Belle Rose Station", price: 32, duration: 10)
Itinerary.create(origin: "Curepipe Central", destination: "Quatre Bornes Central", price: 32, duration: 12)
Itinerary.create(origin: "Curepipe Central", destination: "St Jean Station", price: 32, duration: 11)
Itinerary.create(origin: "Curepipe Central", destination: "Trianon Station", price: 32, duration: 15)
Itinerary.create(origin: "Curepipe Central", destination: "Phoenix Station", price: 32, duration: 16)
Itinerary.create(origin: "Curepipe Central", destination: "Phoenix Mall Station", price: 32, duration: 16)
Itinerary.create(origin: "Curepipe Central", destination: "Palmerston Station", price: 32, duration: 5)
Itinerary.create(origin: "Curepipe Central", destination: "Vacoas Central", price: 32, duration: 6)
Itinerary.create(origin: "Curepipe Central", destination: "Sadally Station", price: 32, duration: 7)
Itinerary.create(origin: "Curepipe Central", destination: "Floreal Station", price: 32, duration: 2)

puts "Itinerary created"
